version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: development-dependencies-env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
      - VITE_ORGANIZATION_ID=${VITE_ORGANIZATION_ID}