import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Moonika",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className="flex justify-center">
        <div className="container w-[90%]">{children}</div>
      </body>
    </html>
  );
}
